### ISSUE TITLE
Editar Documentação e adicionar métricas do projeto

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05-TesouroMineiro#71]
## Descrição

Trabalhando na documentação do projeto.

## Objetivo

O objetivo dessa issue é atualizar e aprimorar a documentação do projeto.

## Pontos Importantes

- [x] Atualizar o Readme para responder todas as dúvidas.
- [x] Adicionar nova imagem do fluxo de processamento.
- [x] Adicionar badges-stats no Readme.
- [x] Adicionar comandos para a executador o frontend localmente.

## Critérios de Aceitação

- [x] As informações estão de acordo com o projeto atual.
- [x] A imagem está de acordo com as ferramentas utilizadas.
- [x] Os basges-stats estão funcianando corretamente.
- [x] É possivel executar o frontend com os comandos apresentados.

**Comment by claudiohsc** [comment]
Tentar focar o Readme orientado a responder "o quê", "o porquê" e o "como" relativos ao projeto.

**Comment by IderlanJ** [comment]
> Tentar focar o Readme orientado a responder "o quê", "o porquê" e o "como" relativos ao projeto.

Ok, farei isso.

**Comment by claudiohsc** [comment]
Depois, só alinhar os títulos.
