### ISSUE TITLE
Melhorar Página de Dados/Consumir Jsons(Testes)

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05-TesouroMineiro#73]
## Descrição

Melhorar a página de dados e encontrar um estrutura de json para consumir os dados 

## Objetivo

Melhorar a página de dados e encontrar um estrutura de json para consumir os dados 

## Pontos Importantes

- [x] Melhorar pag de dados
- [x] Encontrar uma forma de consumir os dados do back
- [x] Estruta do json

## Critérios de Aceitação

- [x] Pag de dados responsiva e funcional
- [x] Estrutura do json

**Comment by claudiohsc** [comment]
Vai ser aplicado a nova estrutura nos códigos do backend.
